import React, { useEffect, useState } from 'react'

const CarCardList = () => {
  const [first, setFirst] = useState([]);
  const fetchCar =async (data:any) => {
    await new Promise(res=>{
      setTimeout(() => {
        setFirst(data);
      }, 2000);
    })
  }
  useEffect(() => {
    fetchCar([
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
      {
        name:'usernaem',
        id:123
      },
    ]);
  },)
  
  return (
    <div>{
      first.map(sdk=>{
        return <p>{sdk?.name}</p>
      })}</div>
  )
}

export default CarCardList